#! /usr/bin/env ruby

require 'pry'
require 'pg'

CONNECTION = PG.connect(dbname: 'expenses')

def display_help
  puts <<~HELP
    An expense recording system

    Commands:

    add AMOUNT MEMO [DATE] - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
  HELP
end

def list_expenses
  result = CONNECTION.exec('SELECT * FROM expenses')
  result.each do |row|
    puts [row['id'].rjust(3), 
          row['created_on'], 
          row['amount'].rjust(12),
          row['memo']].join(' | ')
  end
end

def add_expenses
  if ARGV.size < 3
    puts "You must provide an amount and memo"
  else
    amount = ARGV[1]
    memo = ARGV[2]
    statement = <<~SQL 
      INSERT INTO expenses (amount, memo) 
      VALUES (#{amount}, '#{memo}')
    SQL
    CONNECTION.exec(statement)
  end
end

command = ARGV.first

if ARGV.empty?
  display_help
elsif command == 'list'
  list_expenses 
elsif command == 'add'
  add_expenses
end
