#! /usr/bin/env ruby

require 'pry'
require 'pg'

class ExpenseData
  def initialize
    @connection = PG.connect(dbname: 'expenses')
  end

  def list_expenses
    result = @connection.exec('SELECT * FROM expenses')
    display_expenses(result)
  end
  
  def add_expenses(amount, memo)
      statement = <<~SQL 
        INSERT INTO expenses (amount, memo) 
        VALUES ($1, $2)
      SQL
      @connection.exec_params(statement, [amount, memo])
  end

  def search_expenses(term)
    statement = 'SELECT * FROM expenses WHERE memo ILIKE $1'
    result = @connection.exec_params(statement, ["%#{term}%"])
    display_expenses(result)
  end

  private

  def display_expenses(result)
    result.each do |row|
      puts [row['id'].rjust(3), 
            row['created_on'], 
            row['amount'].rjust(12),
            row['memo']].join(' | ')
    end
  end
end

class CLI
  def initialize
    @app = ExpenseData.new
  end

  def run(arguments)
    command = arguments.first
    
    case command
    when 'list'
      @app.list_expenses 
    when 'add'
      abort "You must provide an amount and memo" unless arguments.size == 3
      @app.add_expenses(arguments[1], arguments[2])
    when 'search'
      @app.search_expenses(arguments[1])
    else
      display_help
    end
  end

  private

  def display_help
    puts <<~HELP
      An expense recording system
  
      Commands:
  
      add AMOUNT MEMO [DATE] - record a new expense
      clear - delete all expenses
      list - list all expenses
      delete NUMBER - remove expense with id NUMBER
      search QUERY - list expenses with a matching memo field
    HELP
  end
end

CLI.new.run(ARGV)

